name: 'Create deploy branch'

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:

permissions:
  contents: write
  deployments: write
  packages: write
  pages: write
  repository-projects: write
  pull-requests: read

jobs:
  refresh-deploy:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DeployKey }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
            ref: deploy
            token: ${{ secrets.PAT }}
      - name: Run Script
        shell: bash
        run: |
          git config --global user.name 'Norbert László'
          git config --global user.email 'laszlo.norbi2000@gmail.com'
          rm -r develop;
          rm -r main;
          git clone --branch main https://github.com/tektektek2000/TrelloPowerUp.git main
          git clone --branch develop https://github.com/tektektek2000/TrelloPowerUp.git develop
          rm -r main/.git
          rm -r develop/.git
          git add --all
          git commit -m "deploy"
          git push
          
